# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39bf293e03dd57ad277f0d569715aca1a46fba8e228f9ae2ea241d09dd4d9652665af4e34bf3ab973c028b9c1fa032f146fe182c6a9b00fa11b1ec08beb4b389

test:
  secret_key_base: 9c9876819fa4270e8e1bb490758d178cc01aeb0ba9f01170c3fbc7cdd7792c1e5fc0c82a7e59ef40e6027ba48b40bf5a88da92010e84e90da86b48a2a5e0a31f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
